### ISSUE TITLE
Does this code still run?

### ISSUE THREAD

**Issue by m172021** [ejb004/egui-wgpu-demo#1]
I updated all the dependencies to 0.27.2, got the code to compile. Then, when I run it in Chrome, I just get a blank screen. Does this code still work ?

Thanks!

**Comment by ejb004** [comment]
No it doesn't work in web assembly, I didn't write that part. It's pretty simple to add though, I learnt following [this](https://sotrh.github.io/learn-wgpu/). It still works on native apps however
